name: Transit Control APK Builder (Android 4 kompatibilis, manuális SDK)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Setup Node.js (Cordova 8 kompatibilis verzió)
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install old Cordova
      run: npm install -g cordova@8.1.2

    - name: Install old Android SDK manually
      run: |
        wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -O sdk-tools.zip
        unzip sdk-tools.zip -d android-sdk
        export ANDROID_HOME=$PWD/android-sdk
        export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools
        yes | android-sdk/tools/bin/sdkmanager --licenses
        android-sdk/tools/bin/sdkmanager "platform-tools" "platforms;android-19" "build-tools;28.0.3"

    - name: Create Transit Control Cordova Project
      run: |
        export ANDROID_HOME=$PWD/android-sdk
        export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools
        cordova create transit-app com.transitcontrol.app "Transit Control"
        cp -r www/* transit-app/www/
        cd transit-app
        cordova platform add android@6.3.0
        cordova build android --debug

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: TransitControl-Debug-APK
        path: transit-app/platforms/android/build/outputs/apk/android-debug.apk
