name: Transit Control APK Builder (Android 4 kompatibilis)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Setup Node.js (Cordova 8 kompatibilis verzió)
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install old Cordova
      run: npm install -g cordova@8.1.2

    - name: Install Android SDK
      uses: android-actions/setup-android@v3

    - name: Create Transit Control Cordova Project
      run: |
        cordova create transit-app com.transitcontrol.app "Transit Control"
        cp -r www/* transit-app/www/
        cd transit-app
        cordova platform add android@6.3.0
        cordova requirements
        cordova build android --debug

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: TransitControl-Debug-APK
        path: transit-app/platforms/android/build/outputs/apk/android-debug.apk
