- name: Install Android SDK manually
      run: |
        wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -O sdk-tools.zip
        unzip sdk-tools.zip -d android-sdk
        yes | android-sdk/tools/bin/sdkmanager --licenses
        export ANDROID_HOME=$PWD/android-sdk
        export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
